//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTS_api.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class bill_detail_ban
    {
        public int id { get; set; }
        public Nullable<int> id_bills_ban { get; set; }
        public Nullable<int> id_sp { get; set; }
        public Nullable<int> sl { get; set; }
        [JsonIgnore]
        public virtual bills_ban bills_ban { get; set; }
        [JsonIgnore]
        public virtual san_pham san_pham { get; set; }
    }
}
