//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTS_api.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class san_pham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public san_pham()
        {
            this.bill_detail_ban = new HashSet<bill_detail_ban>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> id_loai_sp { get; set; }
        public Nullable<int> id_ncc { get; set; }
        public string mota_sp { get; set; }
        public Nullable<double> unit_price { get; set; }
        public Nullable<int> so_luong { get; set; }
        public string image { get; set; }
        public string kich_thuoc { get; set; }
        [JsonIgnore]
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bill_detail_ban> bill_detail_ban { get; set; }
        [JsonIgnore]
        public virtual loai_sp loai_sp { get; set; }
        [JsonIgnore]
        public virtual nha_cung_cap nha_cung_cap { get; set; }
    }
}
